name: vidosc_mac
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch>=2.1.0
    - torchvision>=0.16.0
    - pytorch-lightning>=2.0.0
    - open_clip_torch
    - ffmpeg-python
    - pandas
    - numpy
    - tqdm
    - Pillow
    - torchmetrics
    - scikit-learn
